"""initial_schema

Revision ID: ec43cb151e38
Revises: 
Create Date: 2026-05-19 14:58:44.737058

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa




revision: str = 'ec43cb151e38'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('logs',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('level', sa.Enum('INFO', 'WARNING', 'ERROR', 'CRITICAL', name='loglevel'), nullable=False),
    sa.Column('module', sa.String(length=255), nullable=False),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('details', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_logs_created_at'), 'logs', ['created_at'], unique=False)
    op.create_index(op.f('ix_logs_level'), 'logs', ['level'], unique=False)
    op.create_index(op.f('ix_logs_module'), 'logs', ['module'], unique=False)
    op.create_table('settings',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('key', sa.String(length=255), nullable=False),
    sa.Column('value', sa.Text(), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('is_public', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_settings_key'), 'settings', ['key'], unique=True)
    op.create_table('source_cache',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('source_url', sa.Text(), nullable=False),
    sa.Column('etag', sa.Text(), nullable=True),
    sa.Column('last_modified', sa.Text(), nullable=True),
    sa.Column('last_success_at', sa.DateTime(), nullable=True),
    sa.Column('last_error_at', sa.DateTime(), nullable=True),
    sa.Column('error_count', sa.Integer(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_source_cache_is_active'), 'source_cache', ['is_active'], unique=False)
    op.create_index(op.f('ix_source_cache_source_url'), 'source_cache', ['source_url'], unique=True)
    op.create_table('source_packs',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('slug', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_index(op.f('ix_source_packs_is_active'), 'source_packs', ['is_active'], unique=False)
    op.create_index(op.f('ix_source_packs_is_deleted'), 'source_packs', ['is_deleted'], unique=False)
    op.create_index(op.f('ix_source_packs_slug'), 'source_packs', ['slug'], unique=True)
    op.create_table('users',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('telegram_id', sa.BigInteger(), nullable=False),
    sa.Column('username', sa.String(length=255), nullable=True),
    sa.Column('first_name', sa.String(length=255), nullable=True),
    sa.Column('last_name', sa.String(length=255), nullable=True),
    sa.Column('language_code', sa.String(length=32), nullable=True),
    sa.Column('is_admin', sa.Boolean(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_telegram_id'), 'users', ['telegram_id'], unique=True)
    op.create_table('destinations',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('type', sa.Enum('PRIVATE', 'CHANNEL', 'GROUP', 'FORUM_TOPIC', name='destinationtype'), nullable=False),
    sa.Column('telegram_chat_id', sa.BigInteger(), nullable=False),
    sa.Column('telegram_thread_id', sa.Integer(), nullable=True),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_destinations_is_active'), 'destinations', ['is_active'], unique=False)
    op.create_index(op.f('ix_destinations_is_deleted'), 'destinations', ['is_deleted'], unique=False)
    op.create_index(op.f('ix_destinations_telegram_chat_id'), 'destinations', ['telegram_chat_id'], unique=False)
    op.create_index(op.f('ix_destinations_type'), 'destinations', ['type'], unique=False)
    op.create_index(op.f('ix_destinations_user_id'), 'destinations', ['user_id'], unique=False)
    op.create_table('pack_sources',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('pack_id', sa.Integer(), nullable=False),
    sa.Column('source_url', sa.Text(), nullable=False),
    sa.Column('category', sa.String(length=255), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['pack_id'], ['source_packs.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('pack_id', 'source_url', name='uq_pack_source_url')
    )
    op.create_index(op.f('ix_pack_sources_pack_id'), 'pack_sources', ['pack_id'], unique=False)
    op.create_index(op.f('ix_pack_sources_source_url'), 'pack_sources', ['source_url'], unique=False)
    op.create_table('posts',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('pack_id', sa.Integer(), nullable=True),
    sa.Column('source_url', sa.Text(), nullable=False),
    sa.Column('source_domain', sa.String(length=255), nullable=True),
    sa.Column('title', sa.Text(), nullable=False),
    sa.Column('content', sa.Text(), nullable=True),
    sa.Column('translated_title', sa.Text(), nullable=True),
    sa.Column('translated_content', sa.Text(), nullable=True),
    sa.Column('image_url', sa.Text(), nullable=True),
    sa.Column('telegram_file_id', sa.String(length=512), nullable=True),
    sa.Column('url_hash', sa.String(length=64), nullable=False),
    sa.Column('content_hash', sa.String(length=64), nullable=False),
    sa.Column('similarity_hash', sa.String(length=255), nullable=True),
    sa.Column('status', sa.Enum('NEW', 'PROCESSED', 'PUBLISHED', 'FAILED', name='poststatus'), nullable=False),
    sa.Column('published_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('processing_attempts', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['pack_id'], ['source_packs.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('source_url', name='uq_post_source_url')
    )
    op.create_index(op.f('ix_posts_content_hash'), 'posts', ['content_hash'], unique=False)
    op.create_index(op.f('ix_posts_created_at'), 'posts', ['created_at'], unique=False)
    op.create_index(op.f('ix_posts_pack_id'), 'posts', ['pack_id'], unique=False)
    op.create_index(op.f('ix_posts_published_at'), 'posts', ['published_at'], unique=False)
    op.create_index(op.f('ix_posts_similarity_hash'), 'posts', ['similarity_hash'], unique=False)
    op.create_index(op.f('ix_posts_source_domain'), 'posts', ['source_domain'], unique=False)
    op.create_index(op.f('ix_posts_source_url'), 'posts', ['source_url'], unique=False)
    op.create_index(op.f('ix_posts_status'), 'posts', ['status'], unique=False)
    op.create_index(op.f('ix_posts_url_hash'), 'posts', ['url_hash'], unique=False)
    op.create_table('subscriptions',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('plan', sa.Enum('NEWS', 'CITY', 'DIASPORA', name='subscriptionplan'), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('expires_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_subscriptions_is_active'), 'subscriptions', ['is_active'], unique=False)
    op.create_index(op.f('ix_subscriptions_user_id'), 'subscriptions', ['user_id'], unique=False)
    op.create_table('support_messages',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('telegram_message_id', sa.BigInteger(), nullable=True),
    sa.Column('message_text', sa.Text(), nullable=False),
    sa.Column('status', sa.Enum('OPEN', 'CLOSED', 'IN_PROGRESS', name='supportstatus'), nullable=False),
    sa.Column('admin_reply', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_support_messages_status'), 'support_messages', ['status'], unique=False)
    op.create_index(op.f('ix_support_messages_user_id'), 'support_messages', ['user_id'], unique=False)
    op.create_table('user_pack_subscriptions',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('pack_id', sa.Integer(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['pack_id'], ['source_packs.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'pack_id', name='uq_user_pack')
    )
    op.create_index(op.f('ix_user_pack_subscriptions_pack_id'), 'user_pack_subscriptions', ['pack_id'], unique=False)
    op.create_index(op.f('ix_user_pack_subscriptions_user_id'), 'user_pack_subscriptions', ['user_id'], unique=False)
    op.create_table('deliveries',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('post_id', sa.Integer(), nullable=False),
    sa.Column('destination_id', sa.Integer(), nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'PROCESSING', 'DELIVERED', 'FAILED', 'RETRY', 'SKIPPED', name='deliverystatus'), nullable=False),
    sa.Column('telegram_message_id', sa.BigInteger(), nullable=True),
    sa.Column('retry_count', sa.Integer(), nullable=False),
    sa.Column('last_error', sa.Text(), nullable=True),
    sa.Column('next_retry_at', sa.DateTime(), nullable=True),
    sa.Column('delivered_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['destination_id'], ['destinations.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['post_id'], ['posts.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('post_id', 'destination_id', name='uq_post_destination')
    )
    op.create_index(op.f('ix_deliveries_destination_id'), 'deliveries', ['destination_id'], unique=False)
    op.create_index(op.f('ix_deliveries_next_retry_at'), 'deliveries', ['next_retry_at'], unique=False)
    op.create_index(op.f('ix_deliveries_post_id'), 'deliveries', ['post_id'], unique=False)
    op.create_index(op.f('ix_deliveries_retry_count'), 'deliveries', ['retry_count'], unique=False)
    op.create_index(op.f('ix_deliveries_status'), 'deliveries', ['status'], unique=False)
    op.create_table('routing_rules',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('pack_id', sa.Integer(), nullable=False),
    sa.Column('destination_id', sa.Integer(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['destination_id'], ['destinations.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['pack_id'], ['source_packs.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('pack_id', 'destination_id', name='uq_pack_destination')
    )
    op.create_index(op.f('ix_routing_rules_destination_id'), 'routing_rules', ['destination_id'], unique=False)
    op.create_index(op.f('ix_routing_rules_pack_id'), 'routing_rules', ['pack_id'], unique=False)
    op.create_index(op.f('ix_routing_rules_user_id'), 'routing_rules', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_routing_rules_user_id'), table_name='routing_rules')
    op.drop_index(op.f('ix_routing_rules_pack_id'), table_name='routing_rules')
    op.drop_index(op.f('ix_routing_rules_destination_id'), table_name='routing_rules')
    op.drop_table('routing_rules')
    op.drop_index(op.f('ix_deliveries_status'), table_name='deliveries')
    op.drop_index(op.f('ix_deliveries_retry_count'), table_name='deliveries')
    op.drop_index(op.f('ix_deliveries_post_id'), table_name='deliveries')
    op.drop_index(op.f('ix_deliveries_next_retry_at'), table_name='deliveries')
    op.drop_index(op.f('ix_deliveries_destination_id'), table_name='deliveries')
    op.drop_table('deliveries')
    op.drop_index(op.f('ix_user_pack_subscriptions_user_id'), table_name='user_pack_subscriptions')
    op.drop_index(op.f('ix_user_pack_subscriptions_pack_id'), table_name='user_pack_subscriptions')
    op.drop_table('user_pack_subscriptions')
    op.drop_index(op.f('ix_support_messages_user_id'), table_name='support_messages')
    op.drop_index(op.f('ix_support_messages_status'), table_name='support_messages')
    op.drop_table('support_messages')
    op.drop_index(op.f('ix_subscriptions_user_id'), table_name='subscriptions')
    op.drop_index(op.f('ix_subscriptions_is_active'), table_name='subscriptions')
    op.drop_table('subscriptions')
    op.drop_index(op.f('ix_posts_url_hash'), table_name='posts')
    op.drop_index(op.f('ix_posts_status'), table_name='posts')
    op.drop_index(op.f('ix_posts_source_url'), table_name='posts')
    op.drop_index(op.f('ix_posts_source_domain'), table_name='posts')
    op.drop_index(op.f('ix_posts_similarity_hash'), table_name='posts')
    op.drop_index(op.f('ix_posts_published_at'), table_name='posts')
    op.drop_index(op.f('ix_posts_pack_id'), table_name='posts')
    op.drop_index(op.f('ix_posts_created_at'), table_name='posts')
    op.drop_index(op.f('ix_posts_content_hash'), table_name='posts')
    op.drop_table('posts')
    op.drop_index(op.f('ix_pack_sources_source_url'), table_name='pack_sources')
    op.drop_index(op.f('ix_pack_sources_pack_id'), table_name='pack_sources')
    op.drop_table('pack_sources')
    op.drop_index(op.f('ix_destinations_user_id'), table_name='destinations')
    op.drop_index(op.f('ix_destinations_type'), table_name='destinations')
    op.drop_index(op.f('ix_destinations_telegram_chat_id'), table_name='destinations')
    op.drop_index(op.f('ix_destinations_is_deleted'), table_name='destinations')
    op.drop_index(op.f('ix_destinations_is_active'), table_name='destinations')
    op.drop_table('destinations')
    op.drop_index(op.f('ix_users_telegram_id'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_source_packs_slug'), table_name='source_packs')
    op.drop_index(op.f('ix_source_packs_is_deleted'), table_name='source_packs')
    op.drop_index(op.f('ix_source_packs_is_active'), table_name='source_packs')
    op.drop_table('source_packs')
    op.drop_index(op.f('ix_source_cache_source_url'), table_name='source_cache')
    op.drop_index(op.f('ix_source_cache_is_active'), table_name='source_cache')
    op.drop_table('source_cache')
    op.drop_index(op.f('ix_settings_key'), table_name='settings')
    op.drop_table('settings')
    op.drop_index(op.f('ix_logs_module'), table_name='logs')
    op.drop_index(op.f('ix_logs_level'), table_name='logs')
    op.drop_index(op.f('ix_logs_created_at'), table_name='logs')
    op.drop_table('logs')
    # ### end Alembic commands ###
